pipelines:
  branches:
    master:
      - step:
          name: Build and Test the Website
          image: node:17.0.1
          script:
            - npm install
            - npm install next@10
            - npm run build