pipelines:
  branches:
    master:
      - step:
          name: Build and Test the Website
          image: node:16.13.0
          script:
            - npm install
            - npm install @emotion/react
            - npx next build